/*************************************************************/
/*          proess iperf log data from the USN script        */
/*          generates more detail than process_iperf_log     */
/*          input: log generated by                          */
/*                  measure_iperf <dest_IP> <numtimes>       */
/*          output: tcp_file: #streams vs. throughput        */
/*                  udp_file: #target rate vs. throughput    */
/*                  tcp_sum_file: #streams vs. ave-var throughput     */
/*                  udp_sum_file: #target rate vs. ave-var throughput */
/*                                                                    */
/*          Nagi Rao (raons@ornl.gov)                                 */
/*          Dec 29, 2007                                              */
/**********************************************************************/

#include <stdio.h>
#include <sys/time.h>
#include <time.h>
#include <math.h>
#include <limits.h>
#include <string.h>


#define MAX 10001
#define MAX_TIMES 111
#define MAX_STREAMS 51

int main (argc,argv)
    int argc;
    char *argv[];
{
    FILE *input_file_ptr;
    FILE *output_file;
    float temp1, temp2, mult_fact, add_fact;
    char input_file_name[1000], tcp_file_name[1000], udp_file_name[1000],cline[1000],temp_str[100];
    char temp1_str[100],temp2_str[100],temp3_str[100],temp4_str[100],temp5_str[100],temp6_str[100];
    char temp7_str[100],temp8_str[100],temp9_str[100],ch;
    char tcp_sum_file[100],udp_sum_file[100];
    int num,num_times,i,j,k,num_streams,i1,done,k1;
    float fk,fi1;
    float A[MAX_STREAMS][MAX_TIMES];
    float B[MAX_STREAMS][MAX_TIMES];
    float mean[MAX_STREAMS];
    float variance[MAX_STREAMS];

    if (argc!=8) {
        fprintf(stderr, "usage: %s <input_file_name>-<max_num_streams><num_times>; <tcp_file_name> <udp_file_name> <tcp_sum_file> <udp_sum_file>\n",
                argv[0]);
        return(1);
    }

    sscanf(argv[1],"%s",input_file_name);
    sscanf(argv[2],"%d",&num_streams);
    sscanf(argv[3],"%d",&num_times);
    sscanf(argv[4],"%s",tcp_file_name);
    sscanf(argv[5],"%s",udp_file_name);
    sscanf(argv[6],"%s",tcp_sum_file);
    sscanf(argv[7],"%s",udp_sum_file);

    input_file_ptr=fopen(input_file_name,"r");

    /* process TCP data */
    output_file=fopen(tcp_file_name,"w");

    fi1=0;
    for (j=1;j<=num_streams;j++) {
        for (i=1;i<=num_times;i++) {
            // fprintf(output_file,"%f %f %f\n",((float) i), ((float) j), fi1);
            A[j][i]=0;
        }
        // fprintf(output_file,"\n");
    }
    /* handle single streams */
    for (i=1;((i<=num_times)&&(!feof(input_file_ptr)));i++) {
        for (j=1;((j<=6)&&(!feof(input_file_ptr)));j++) {
            fgets(cline,LINE_MAX,input_file_ptr);
        }
        if (!(feof(input_file_ptr))) {
            sscanf(cline,"%s %s %s %s %f %s %f",temp_str,temp1_str,temp2_str,temp3_str,&fk,temp4_str,&fi1);
            // fprintf(output_file,"(%d,1) - %s\n",i,cline);
            // fprintf(output_file,"1.0 1.0 %f\n",fi1);
            A[1][i]=fi1;
        }
    }

    /* handle multiple streams */
    for (j=2;((j<=num_streams)&&(!feof(input_file_ptr)));j++) {
        for (i=1;((i<=num_times)&&(!feof(input_file_ptr)));i++) {
            fgets(cline,LINE_MAX,input_file_ptr);
            while((!(strncmp(cline,"[SUM]",5)==0))&&(!(feof(input_file_ptr)))) {
                fgets(cline,LINE_MAX,input_file_ptr);
            }
            if (!(feof(input_file_ptr))) {
                // fprintf(output_file,"(%d,%d) - %s\n",i,j,cline);
                sscanf(cline,"%s %s %s %f %s %f",temp_str,temp1_str,temp2_str,&fk,temp4_str,&fi1);
                // fprintf(output_file,"%f %f %f\n",((float) j), ((float) j), fi1);
                A[j][i]=fi1;
            }
        }
    }
    for (j=1;j<=num_streams;j++) {
        for (i=1;i<=num_times;i++) { fprintf(output_file,"%f ",A[j][i]); }
        fprintf(output_file,"\n");
    }
    fclose(output_file);

    for (j=1;j<=num_streams;j++) {
        mean[j]=0;
        for (i=1;i<=num_times;i++) { mean[j]+=A[j][i]; }
        mean[j]=mean[j]/((float) num_times);
    }
    for (j=1;j<=num_streams;j++) {
        variance[j]=0;
        for (i=1;i<=num_times;i++) { variance[j]+=(A[j][i]-mean[j])*(A[j][i]-mean[j]); }
        variance[j]=variance[j]/((float) num_times);
        variance[j]=sqrt(variance[j]);
    }

    output_file=fopen(tcp_sum_file,"w");
    for (j=1;j<=num_streams;j++) {
        fprintf(output_file,"%f %f %f\n", ((float) j), mean[j],variance[j]);
    }
    fclose(output_file);
    /* generate summary of tcp average and variance */

    /* process UDP data */
    // output_file=fopen(udp_file_name,"w");
    fi1=0;
    num_streams=11;
    for (j=1;j<=num_streams;j++) {
        for (i=1;(i<=10)||(i<=num_times);i++) {
            // fprintf(output_file,"%f %f %f\n",((float) i), ((float) j), fi1);
            A[j][i]=0;
            B[j][i]=0;
        }
        // fprintf(output_file,"\n");
    }
    /* skip two measurements */
    while((!(strncmp(cline,"[  3] Server Report",15)==0))&&(!(feof(input_file_ptr)))) {
        fgets(cline,LINE_MAX,input_file_ptr);
    }
    fgets(cline,LINE_MAX,input_file_ptr);

    output_file=fopen("trace_file","w");
    for (j=1;((j<=num_streams)&&(!feof(input_file_ptr)));j++) {
        for (i=1;((i<=num_times)&&(!feof(input_file_ptr)));i++) {
            fgets(cline,LINE_MAX,input_file_ptr);
            while((!(strncmp(cline,"[  3] Server Report",15)==0))&&(!(feof(input_file_ptr)))) {
                fgets(cline,LINE_MAX,input_file_ptr);
            }
            if (!(feof(input_file_ptr))) {
                fgets(cline,LINE_MAX,input_file_ptr);
                // fprintf(output_file,"(%d,%d) - %s\n",i,j,cline);
                sscanf(cline,"%s %s %s %s %s %s %f %s %s %s %s",
                        temp_str,temp1_str,temp2_str,temp3_str,temp4_str,temp5_str,
                        &fi1,temp6_str,temp7_str,temp8_str,temp9_str);
                if (temp6_str[0]=='K') { fi1=fi1/1000.0;};
                // fprintf(output_file,"%f %f %f  - %s -%d\n",
                //	((float) j), ((float) j), fi1, temp9_str,strlen(temp9_str));

                A[j][i]=fi1;

                done=0;
                for (k=0;(k<strlen(temp9_str))&& (done==0); k++){
                    if (temp9_str[k]=='/') { done=k;};
                    // fprintf(output_file,"%c \n",temp9_str[k]);
                }
                for (k1=0;k+k1<strlen(temp9_str); k1++) {
                    temp_str[k1]=temp9_str[k1+k];
                }
                // fprintf(output_file,"%s --- %s \n",temp9_str,temp_str);
                sscanf(temp9_str,"%f",&temp1);
                sscanf(temp_str,"%f",&temp2);
                // fprintf(output_file,"%f %f \n",temp1,temp2);
                if (temp2 <=0) { B[j][i]=0; } else { B[j][i]=temp1/temp2; }
                // else { B[j][i]=10.0; }
            }
        }
    }
    fclose(output_file);

    A[1][1]=A[1][2];
    A[num_streams][num_times]=A[num_streams][num_times-1];
    output_file=fopen(udp_file_name,"w");
    for (j=1;j<=num_streams;j++) {
        for (i=1;i<=num_times;i++) { fprintf(output_file,"%f ",A[j][i]); }
        fprintf(output_file,"\n");
    }
    fclose(output_file);

    output_file=fopen("loss_file","w");
    for (j=1;j<=num_streams;j++) {
        for (i=1;i<=num_times;i++) { fprintf(output_file,"%f ",B[j][i]); }
        fprintf(output_file,"\n");
    }
    fclose(output_file);

    fclose(input_file_ptr);

    for (j=1;j<=num_streams;j++) {
        mean[j]=0;
        for (i=1;i<=num_times;i++) { mean[j]+=A[j][i]; }
        mean[j]=mean[j]/((float) num_times);
    }
    for (j=1;j<=num_streams;j++) {
        variance[j]=0;
        for (i=1;i<=num_times;i++) { variance[j]+=(A[j][i]-mean[j])*(A[j][i]-mean[j]); }
        variance[j]=variance[j]/((float) num_times);
        variance[j]=sqrt(variance[j]);
    }

    output_file=fopen(udp_sum_file,"w");
    for (j=1;j<=num_streams;j++) {
        fprintf(output_file,"%f %f %f\n", (float) j, mean[j],variance[j]);
    }
    fclose(output_file);
}

